// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Admin struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	ProfilePic sql.NullString `json:"profile_pic"`
}

type FAQ struct {
	ID       int32  `json:"id"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type Task struct {
	ID          uuid.UUID    `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Link        string       `json:"link"`
	Question    string       `json:"question"`
	Answer      string       `json:"answer"`
	Reward      int32        `json:"reward"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type TaskUser struct {
	UserID     int64         `json:"user_id"`
	TaskID     uuid.UUID     `json:"task_id"`
	TotalTries sql.NullInt32 `json:"total_tries"`
	StartedAt  sql.NullTime  `json:"started_at"`
	FinishedAt sql.NullTime  `json:"finished_at"`
}

type User struct {
	ID           int64          `json:"id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	PhoneNumber  string         `json:"phone_number"`
	ReferalCode  int64          `json:"referal_code"`
	ReferalCount sql.NullInt32  `json:"referal_count"`
	ReferredBy   sql.NullInt64  `json:"referred_by"`
	Language     sql.NullString `json:"language"`
	ProfilePic   sql.NullString `json:"profile_pic"`
	NetBalance   pgtype.Numeric `json:"net_balance"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Withdrawal struct {
	ID        uuid.UUID      `json:"id"`
	UserID    sql.NullInt64  `json:"user_id"`
	Amount    pgtype.Numeric `json:"amount"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	Status    string         `json:"status"`
}
